Add Sunil_Tajpuriya to Before I Die
BeforeIDieCode/BeforeIDieAchievements pull request #198
Opened 2023-10-13 08:54 UTC by tajpuriya27

I am adding `Sunil Tajpuriya` to Before I Die.

2023-10-13 09:14 UTC, XanderRubio commented on CONTRIBUTION-GUIDELINES.md
Hi @tajpuriya27,

Thank you for your time in assisting and contributing! Can you please confirm if you intend to make changes to the CONTRIUBTION-GUIDELINES.md file as when reviewing it is showing that you have made changes, and I wanted to make sure you intended to do so and then ask what did you do differently before I merge. Please let me know and thank you!

2023-10-13 09:17 UTC, XanderRubio requested changes
Excellent your text and image show up great on the preview deployment, and striving to live a purposeful life of rishes and supporting and providing for your parents is noble, and I wish you the best in your pursuit Additionally, congratulations on being the first contributor from Nepal! It's a unique flag. Please confirm if you intend to make changes to the CONTRIBUTION-GUIDELINES.md. After, I will go ahead and merge.

2023-10-15 14:49 UTC, tajpuriya27 commented on CONTRIBUTION-GUIDELINES.md
There are no specific changes on the CONTRIBUTION-GUIDELINES.md file. The extension in my IDE has put extra line spaces between lines in the md file. 
I think you should ignore the changes on that file. Thank you for your quick response!

2023-10-16 16:09 UTC, XanderRubio commented on CONTRIBUTION-GUIDELINES.md
Great, and thank you, @tajpuriya27, for the clarification!

2023-10-16 16:17 UTC, XanderRubio approved these changes
Excellent @tajpuriya27! Your contribution looks great on the website, and I am going ahead with merging your work now. Thank you for your time in contributing and sharing that you want to make your parents proud. Make it happen!

2023-10-16 16:20 UTC, merged

2023-10-16 16:20 UTC, XanderRubio commented
@tajpuriya27   Your pull request has been successfully merged!!! Congratulations <img alt="Bottle with Popping Cork" width="25" height="25" src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Food/Bottle%20with%20Popping%20Cork.png"><img alt="Bottle with Popping Cork" width="25" height="25" src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Food/Bottle%20with%20Popping%20Cork.png"><img alt="Bottle with Popping Cork" width="25" height="25" src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Food/Bottle%20with%20Popping%20Cork.png"><img alt="Double Exclamation Mark" width="25" height="25" src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Symbols/Double%20Exclamation%20Mark.png"><img alt="Double Exclamation Mark" width="25" height="25" src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Symbols/Double%20Exclamation%20Mark.png"><img alt="Double Exclamation Mark" width="25" height="25" src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Symbols/Double%20Exclamation%20Mark.png">. Make it happen for living a life of value and making your parents proud!

 If you haven't already, please go ahead and star <img alt="Glowing Star" width="25" height="25" src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Glowing%20Star.png"><img alt="Glowing Star" width="25" height="25" src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Glowing%20Star.png"><img alt="Glowing Star" width="25" height="25" src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/Glowing%20Star.png">this repo and you are more than welcome to continually contribute to this project by assisting with our [open issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues), or adding your own new open issues, and additionally you can get an idea of ideas we have to continually grow this project further as technology and tech stack continually evolve by looking at the [ROADMAP](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md) for the project. Have a great day, and thank you for taking the time to contribute, Sunil! You can view your contribution now on the [live link](https://before-i-die-achievements.vercel.app/). Have a great rest of your day, and I will be sending you an invite to be a member of the Before I Die Code now.